main/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parser.urls'))
]

main/parser/urls.py
from django.urls import path
from django.http import HttpResponse
from .views import *
from .models import *


urlpatterns = [
    path('', welcome_screen, name='welcome_screen'),
    path('shareslist', SharesListView.as_view(), name='shares_list'),
    path('welcome', welcome_screen, name='welcome_screen'),
    path('get_tks_shares',  get_tks_shares, name='get_tks_shares'),
    path('yahoo_parser_news', yahoo_parser_news, name='yahoo_parser_news'),
    path('news_table_report/<int:page>/', news_table_report, name='news_table_report'),
    path('get_yahoo_ajax_progress_bar_data', get_yahoo_ajax_progress_bar_data, name='get_yahoo_ajax_progress_bar_data'),
    path('preferences', PreferencesListView.as_view(), name='preferences'),
    path('preference_create', PreferenceCreate.as_view(), name='preference_create'),
    path('preference_update/<int:pk>/', PreferenceUpdate.as_view(), name='preference_update'),
    path('preference_delete/<int:pk>/', PreferenceDelete.as_view(), name='preference_delete'),
    path('preference_check_default', check_default_preferencies, name='preference_check_default'),
    path('preferences_reset_to_defaults', reset_to_defaults, name='preferences_reset_to_defaults'),
    path('reset_news_parser', reset_news_parser, name='reset_news_parser'),
    path('news_key_words_list', NewsKeyWordListView.as_view(), name='news_key_words_list'),
    path('news_key_words_create', NewsKeyWordsCreate.as_view(), name='news_key_words_create'),
    path('news_key_words_update/<int:pk>/', NewsKeyWordsUpdate.as_view(), name='news_key_words_update'),
    path('news_key_words_delete/<int:pk>/', NewsKeyWordsDelete.as_view(), name='news_key_words_delete'),
    path('get_cnn_fear_and_greed_stats', get_cnn_fear_and_greed_stats, name='get_cnn_fear_and_greed_stats'),
    path('get_finviz_futures_data', get_finviz_futures_data, name='get_finviz_futures_data'),
    path('get_finviz_crypto_data', get_finviz_crypto_data, name='get_finviz_crypto_data'),
    path('get_top_news', get_top_news, name='get_top_news'),
    path('get_news_update_status', get_news_update_status, name='get_news_update_status'),
    path('launch_news_update_background', launch_news_update_background, name='launch_news_update_background'),
    path('get_top_shorts', get_finviz_top_shorts, name='get_top_shorts'),
    path('get_candles', get_candles, name='get_candles'),
    path('get_calendar_events', get_calendar_events, name='get_calendar_events'),
    path('get_tipranks_data/<str:ticker>/', get_tipranks_data, name='get_tipranks_data'),
    path('get_fail_to_deliver_list', get_fail_to_deliver_list, name='get_fail_to_deliver_list'),
    path('ttest',  ttest, name='ttest'),
]

main/parser/models.py
from builtins import str
from tinkoff.invest import Client
from django.db import models
from django.urls import reverse
from django.core import serializers
from datetime import datetime
from tinkoff.invest import Client
from django.db.models.functions import Upper


class Share(models.Model):
    figi = models.CharField(verbose_name='figi', max_length=12)
    ticker = models.CharField(verbose_name='ticker', max_length=20)
    class_code = models.CharField(verbose_name='class_code', max_length=20)
    isin = models.CharField(verbose_name='isin', max_length=12)
    lot = models.IntegerField(verbose_name='lot', null=True)
    currency = models.CharField(verbose_name='currency', max_length=5)
    short_enabled_flag = models.BooleanField(verbose_name='shorts enabled', null=True)
    name = models.CharField(verbose_name='name', max_length=80)
    exchange = models.CharField(verbose_name='exchange', max_length=80)
    ipo_date = models.DateTimeField(verbose_name='ipo_date', null=True)
    issue_size = models.BigIntegerField(verbose_name='issue_size', null=True)
    country_of_risk = models.CharField(verbose_name='country_of_risk', max_length=2)
    country_of_risk_name = models.CharField(verbose_name='country_of_risk_name', max_length=80)
    sector = models.CharField(verbose_name='sector', max_length=25)
    issue_size_plan = models.BigIntegerField(verbose_name='issue_size_plan', null=True)
    otc_flag = models.BooleanField(verbose_name='otc_flag', default=False, null=True)
    buy_available_flag = models.BooleanField(verbose_name='buy_available_flag', default=False, null=True)
    sell_available_flag = models.BooleanField(verbose_name='sell_available_flag', default=False, null=True)
    div_yield_flag = models.BooleanField(verbose_name='div_yield_flag', default=False, null=True)
    api_trade_available_flag = models.BooleanField(verbose_name='api_trade_available_flag', default=False, null=True)
    date_added = models.DateTimeField(verbose_name='date_added', default=datetime.now())

    class Meta:
        verbose_name = 'акция'
        verbose_name_plural = 'акции'
        ordering = ['ticker']


class NewsKeyWord(models.Model):
    keyword = models.CharField(verbose_name='keyword', max_length=30)

    class Meta:
        verbose_name = 'ключевое слово'
        verbose_name_plural = 'ключевые слова'
        ordering = [Upper('keyword'), 'keyword']

    def get_absolute_url(self):
        return reverse('news_key_words_list')

    def get_update_url(self):
        return reverse('news_key_words_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('news_key_words_delete', kwargs={'pk': self.pk})


class News(models.Model):
    description = models.TextField(verbose_name='description')
    link = models.TextField(verbose_name='link')
    pubDate = models.DateTimeField(verbose_name='pubDate')
    title = models.TextField(verbose_name='title')

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        ordering = ['-pubDate']

    # def as_json(self):
    #     return dict(
    #         description=self.description,
    #         link=self.link,
    #         pubDate=self.pubDate,
    #         title=self.title
    #     )


class Preference(models.Model):
    name = models.CharField(verbose_name='name', max_length=40, unique=True)
    value = models.TextField(verbose_name='value')
    default_value = models.TextField(verbose_name='default_value', null=True)
    description = models.TextField(verbose_name='description', null=True)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('preferences')

    def get_update_url(self):
        return reverse('preference_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('preference_delete', kwargs={'pk': self.pk})


class ServiceVariables(models.Model):
    name = models.CharField(verbose_name='name', max_length=80, unique=True)
    value = models.CharField(verbose_name='value', max_length=80, null=True)

main/parser/forms.py
from django import forms
from .models import Preference, NewsKeyWord



class NewsKeyWordForm(forms.ModelForm):

    class Meta:
        model = NewsKeyWord
        fields = '__all__'
        widgets = {
            'keyword': forms.TextInput(attrs={'class': 'form-control'}),
        }


class PreferenceForm(forms.ModelForm):

    class Meta:
        model = Preference
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'value': forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 120px'}),
            'default_value': forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 120px'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'style': 'height: 90px'}),
        }

main/parser/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google" content="notranslate">
    <title>SadDinamo parsing tks</title>
    {% load static %}
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'bootstrap_icons/font/bootstrap-icons.min.css' %}">
</head>

<body data-bs-theme="dark">
<!--   Main upper menu   -->
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <a class="navbar-brand me-2 link-secondary" href="{% url 'welcome_screen' %}">
            <i class="bi bi-house fs-3"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownReports" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">User menu
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'shares_list' %}">
                                <i class="fa-solid fa-rectangle-list"></i> Shares report</a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'get_tks_shares' %}">
                                {% csrf_token %}
                                <button id="get-tks-shares-btn" class="dropdown-item border-0">
                                    <i class="fa-solid fa-bolt"></i> Get tks shares
                                </button>
                            </form>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'news_table_report' page=1 %}">
                                <i class="fa-solid fa-rectangle-list"></i> News report</a>
                        </li>
                        <li class="nav-item">
                            <button id="yahoo_parser_news_show-btn" class="dropdown-item border-0">
                                <i class="fa-solid fa-bolt"></i> Parse yahoo tickers news
                            </button>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'news_key_words_list' %}">
                                <i class="fa-solid fa-gears"></i> News key-words management</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownActions" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Admin menu
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'preferences' %}">
                                <i class="fa-solid fa-gears"></i> Preferences</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'ttest' %}">
                                <i class="fa-solid fa-microscope"></i> Test action </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <div>
                <div id="updating-news-label" class="small mb-0 mx-0 navbar-text d-none"></div>
                <i id="updating-news-wheel" class="fa-solid fa-cog fa-spin d-none"></i>
                <div class="progress" style="height: 3px;">
                    <div class="progress-bar bg-secondary" id="updating-news-progressbar" role="progressbar"
                         style="width: 25%;" aria-valuenow="25"
                         aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div title="Rerun news update">
                <div id="updating-news-rerun-button"
                     class="btn btn-outline-light d-none border border-secondary-subtle rounded px-2 mx-2
                   text-secondary">
                    <i class="fa-solid fa-rotate"></i>
                </div>
            </div>
        </div>

    </div>
</nav>

<!--   Toasts section   -->
<div class="toast-container position-absolute top-2 end-0" style="z-index:2" id="toasts-section">
    {% if messages %}
    {% for message in messages %}
    <div class="toast align-items-center text-white bg-{% if message.tags %}{{ message.tags }}{% endif %} border-0"
         role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
        <div class="d-flex">
            <div class="toast-body">
                {{ message }}
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                    aria-label="Close"></button>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>

<!--  Progress bar in modal window: parsing Yahoo.Finance news  -->
<div class="modal fade" id="yahooFinanceProgressBarModal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="yahooFinanceProgressBarModalLabel">Parsing Yahoo.Finance news</h5>
            </div>
            <div class="modal-body">
                <div class="d-flex flex-column">
                    <div class="progress">
                        <div id="yahooFinanceProgressBar"
                             class="progress-bar progress-bar-striped progress-bar-animated"
                             role="progressbar"
                             style="width: 0%;" aria-valuenow="0"
                             aria-valuemin="0" aria-valuemax="100">
                        </div>
                    </div>
                    <div id="yahooFinanceProgressBarLabel" class="mr-auto"></div>
                </div>
            </div>

            <div class="modal-footer d-flex flex-row">
                <a id="yahoo_parser_news-btn" href="{% url 'yahoo_parser_news'%}" class="btn btn-primary col col-3">
                    Run
                </a>
                <div class="flex-grow-1"></div>
                <button type="button" class="btn btn-secondary col col-3" data-bs-dismiss="modal">
                    Hide
                </button>
            </div>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<script src="{% static 'js/toasts.js' %}"></script>
<script src="{% static 'js/yahooFinanceProgressBarModal.js' %}"></script>

</body>

</html>

main/parser/templates/news_table_report.html
{% extends 'base.html' %}

{% block content %}

<div class="d-flex my-2">
    <h2 class="mx-auto">News table report</h2>
</div>

<div class="d-flex">
    <div class="mx-auto d-flex flex-wrap justify-content-center col-10">

        <nav aria-label="..." class="">
            <ul class="pagination">
                {% if news_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href=" {% url 'news_table_report' 1 %}?val={{ search_word }}">First page</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">First page</a>
                </li>
                {% endif %}

                {% if news_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href=" {% url 'news_table_report' news_list.previous_page_number %}?val={{ search_word }} ">&laquo</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&laquo</a>
                </li>
                {% endif %}

                {% for n in news_list.paginator.page_range %}
                {% if news_list.number == n %}
                <li class="page-item active">
                    <a class="page-link" href="{% url 'news_table_report' n %}?val={{ search_word }}">{{ n }}</a>
                </li>
                {% elif n|add:-4 >= news_list.number and n <= 7 %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'news_table_report' n %}?val={{ search_word }}">{{ n }}</a>
                </li>
                {% elif n|add:4 <= news_list.number and n >= news_list.paginator.num_pages|add:-6 %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'news_table_report' n %}?val={{ search_word }}">{{ n }}</a>
                </li>
                {% elif n >= news_list.number|add:-3 and n <= news_list.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'news_table_report' n %}?val={{ search_word }}">{{ n }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if news_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href=" {% url 'news_table_report' news_list.next_page_number %}?val={{ search_word }} ">&raquo</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo</a>
                </li>
                {% endif %}

                {% if news_list.number != news_list.paginator.num_pages %}
                <li class="page-item">
                    <a class="page-link" href=" {% url 'news_table_report' news_list.paginator.num_pages %}?val={{ search_word }} ">Last page</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Last Page</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        <div class="mx-0 mx-md-2"></div>
        <form class="d-flex mb-4 col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-3">
            {% if search_word %}
                <input class="form-control me-2" name="val" type="search" value="{{ search_word }}" placeholder="Search in title and description" aria-label="Search">
            {% else %}
                <input class="form-control me-2" name="val" type="search" placeholder="Search in title and description" aria-label="Search">
            {% endif %}
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
    </div>
</div>

<div id="newstablewrapper" class="col col-11 mx-auto">
    <div class="table-responsive">
        <table id="newstable" class="table table-striped table-bordered table-sm">
            <thead>
            <!--            <th><input type="checkbox" id="checkall"></th>-->
            <th class="text-center"><h3>Title</h3></th>
            <th class="text-center"><h3>Description</h3></th>
            </thead>
            <tbody>
            {% for news_item in news_list %}
            <tr>
                <!--                <td><input type="checkbox" class="checkthis"></td>-->
                <td><p><a href="{{ news_item.link }}" target="_blank">{{ news_item.title }}</a></p>
                    {{ news_item.pubDate|date:"Y-M-d H:m" }}
                </td>
                <td>{{ news_item.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}